In [1]:
%pip install --upgrade pip
%pip install numpy pandas
%pip install torch torchvision

# Tensor

텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조이다. `Pytorch`에서는 텐서를 사용하여 모델의 입려과 출력뿐만 아니라 모델의 매개변수를 부호화(encode) 한다.

GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다는 점을 제외하면, 텐서는 Numpy의 ndarray와 매우 유사하다.

In [2]:
import torch
import numpy as np

## 텐서 초기화하기

### 1. 데이터로부터 직접(directly) 생성하기

데이터로부터 직접 텐서를 생성할 수 있으며, 데이터의 자료형(datatype)은 자동으로 유추한다.

### 2. Numpy 배열로부터 생성하기

텐서는 Numpy 배열로 생성할 수 있으며, 그 반대도 가능하다.

### 3. 다른 텐서로부터 생성하기

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지한다.

### 4. 무작위(random) 또는 상수(constant) 값을 사용하기

'shape'는 텐서의 차원(dimension)을 나타내는 튜플(tuple)로 출력 텐서의 차원을 결정한다.

In [3]:
# 1. 데이터로부터 직접 생성하기
x_data = torch.tensor(
    [[1, 2], [3, 4]]
)

In [4]:
# 2. Numpy 배열로부터 생성하기
x_np = torch.from_numpy(
    np.array([[1, 2], [3, 4]])
)

In [5]:
# 3. 다른 텐서로부터 생성하기
print(f"Ones Tensor:")
print(torch.ones_like(x_data))
print()

print(f"Randon Tensor:")
print(torch.rand_like(x_data, dtype=torch.float))

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Randon Tensor:
tensor([[0.7852, 0.5010],
        [0.8921, 0.5688]])


In [6]:
# 4. 무작위(random) 또는 상수(constant) 값을 사용하기
shape = (2, 3,)

print(f"Random Tensor:")
print(torch.rand(shape))
print()

print(f"Ones Tensor:")
print(torch.ones(shape))
print()

print(f"Zeros Tensor:")
print(torch.zeros(shape))

Random Tensor:
tensor([[0.3325, 0.1142, 0.1078],
        [0.7744, 0.8177, 0.3097]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성(Attribute)

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.

In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서의 연산(Operation)

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등, 100가지 이상의 텐서 연산들을 실행할 수 있다.

각 연산들은 GPU에서 실행할 수 있다.

In [8]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

In [9]:
# Numpy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
# 텐서 합치기
# torch.cat()을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다.
print(
    torch.cat(
        [tensor, tensor, tensor],
        dim=1
    )
)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
# 텐서 곱하기 (요소별 곱, element-wise product)
print("tensor.mul(tensor):")
print(tensor.mul(tensor))
print()

print("tensor * tensor:")
print(tensor * tensor)

tensor.mul(tensor):
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor:
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
# 텐서 곱하기 (행렬 곱, matrix multiplication)
print("tensor.matmul(tensor.T):")
print(tensor.matmul(tensor.T))
print()

print("tensor @ tensor.T:")
print(tensor @ tensor.T)

tensor.matmul(tensor.T):
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.T:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [13]:
# 바꿔치기 연산 (권장하지 않음)
print(tensor)
print()

tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Numpy 변환(Bride)

CPU 상의 텐서와 Numpy 배열은 메모리 공산을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

In [14]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
